import { cn } from '@/lib/utils'
import './globals.css'
import Script from 'next/script'
import type { Metadata } from 'next'
import NavBar from '@/components/NavBar'
import Provider from '@/components/Provider'
import { Toaster } from '@/components/ui/toaster'
import "simplebar-react/dist/simplebar.min.css"
export const metadata: Metadata = {
  title: 'Doc🧐 mentor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <head>
      <Script id="pdf-eval-settings" strategy="beforeInteractive">
          {`window.isEvalSupported = false;`}
      </Script>
      </head>
      <body className={cn(
        'min-h-screen font-sans antialiased grainy'
      )}>
        <Provider>
          <Toaster />
           <NavBar/>
          {children}
        </Provider>
           
      </body>
    </html>
  ) 
}
 