import { cn } from '@/lib/utils'
import './globals.css'

import type { Metadata } from 'next'
import NavBar from '@/components/NavBar'
import Provider from '@/components/Provider'
import { Toaster } from '@/components/ui/toaster'

export const metadata: Metadata = {
  title: 'Doc🧐 mentor',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className='light'>
      <body className={cn(
        'min-h-screen font-sans antialiased grainy'
      )}>
        <Provider>
          <Toaster />
           <NavBar/>
          {children}
        </Provider>
           
      </body>
    </html>
  ) 
}
 